#!/usr/bin/env bash
# Install the memex-desmos fork and warm its index. SETUP step, never part of
# `python -m desmos tui` launch. Absent fork => the <recall> syscall refuses in
# prose and the model falls back to `rg` over .desmos/events/*.jsonl.
#
# WHY A FORK: upstream memex has no adapter mechanism. SourceKind is a closed
# clap enum (vendor/memex/src/types.rs: Claude|Codex|Opencode|Cursor|Pi|
# OpenClaw|Copilot|Hermes). Reading desmos events needs a fork that adds:
#   - SourceKind::Desmos
#   - src/sources/desmos.rs walking <root>/.desmos/events/*.jsonl by byte
#     offset (incremental), parsing prompt / speech / complete.thinking /
#     result-done / subagent / child events. NEVER trajectory/*.json or
#     harness.sqlite3.
# The parity fixture is generated by the golden recorder, never handwritten.
#
# DISTRIBUTION: memex pulls in tantivy + usearch + ort — those must NOT enter
# the desmos build. So memex ships as an external binary, installed here, not
# as a workspace crate.
set -euo pipefail

MEMEX="${DESMOS_MEMEX:-memex}"
# Point these at the fork once it is published/pinned. Kept as env so this
# script needs no edit to track a new rev.
FORK_REPO="${MEMEX_DESMOS_REPO:-}"
FORK_REV="${MEMEX_DESMOS_REV:-}"

# The fork detector: stock memex clap-rejects an unknown --source; the fork
# answers. Exit 0 == the desmos source exists. This is the same probe
# desmos/state/recall.py and recall_check.py use.
# A query token is required: without it the fork also exits nonzero (missing
# QUERY). The fork answers `[]` for any query; stock clap-rejects --source.
probe() { "$MEMEX" search __probe__ --source desmos --limit 1 >/dev/null 2>&1; }

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDOR_FORK="$REPO/vendor/memex"

if probe; then
  echo "memex-setup: memex-desmos fork already on PATH ($("$MEMEX" --version 2>/dev/null || echo memex))"
elif [ -f "$VENDOR_FORK/src/sources/desmos.rs" ] && command -v cargo >/dev/null 2>&1; then
  # The fork lives vendored (a gitignored clone with SourceKind::Desmos added,
  # same as build-fff-python.sh builds fff from vendor/fff). Build from it.
  echo "memex-setup: building memex-desmos from $VENDOR_FORK"
  cargo install --path "$VENDOR_FORK" --locked memex 2>/dev/null \
    || cargo install --path "$VENDOR_FORK" memex
else
  if [ -z "$FORK_REPO" ] || [ -z "$FORK_REV" ]; then
    cat >&2 <<'EOF'
memex-setup: the memex-desmos fork is not installed and no pin is configured.

Set MEMEX_DESMOS_REPO and MEMEX_DESMOS_REV to the fork (memex + SourceKind::Desmos
+ src/sources/desmos.rs, see header) and re-run, e.g.:

  MEMEX_DESMOS_REPO=https://github.com/<owner>/memex-desmos \
  MEMEX_DESMOS_REV=<sha> scripts/memex-setup.sh

Until then <recall> refuses in prose; use `rg` over .desmos/events/*.jsonl.
EOF
    exit 1
  fi
  if ! command -v cargo >/dev/null 2>&1; then
    echo "memex-setup: cargo not found; install Rust to build the fork" >&2
    exit 1
  fi
  echo "memex-setup: installing memex-desmos from $FORK_REPO @ $FORK_REV"
  cargo install --git "$FORK_REPO" --rev "$FORK_REV" --locked memex
fi

if ! probe; then
  echo "memex-setup: install finished but the desmos source is still missing" >&2
  exit 1
fi

# Warm the index so first <recall> is fast, not a 30s cold-index timeout.
echo "memex-setup: indexing"
exec "$MEMEX" index
